(function() {
  "use strict";

  // Can use React.createElements with 3 arguments (type, properties and content)
  // But better to use JSX directly, with Babel

  const ProductImage = (props) => {
    return <img src={`../../../assets/${props.color}.jpg`} alt="Shoe" />;
  }

  const SizeSelector = (props) => {
    const sizeOptions = () => {
      return props.sizes.map(num => {
        return (
          // Everytime you generate a list of items that is generated by a helper function, you need a key
          <option value={num} key={num}>{num}</option>
        )
      });
    }

    return (
      <div className="field-group">
        <label htmlFor="size-options">Size:</label>
        <select defaultValue={props.size} name="sizeOptions" id="size-options">
          {sizeOptions()}
        </select>
      </div>
    )
  }

  // Element to be rendered, 3 arguments, what type of elt we are creating, props we are gonna passed into this elt, and whatever should be in this elt
  const ProductCustomizer = (props) => {
    // Array destructuring
    let [size, setSize] = React.useState(8);
    // useState is a Hook that adds React state to a function component
    // initialize useState with 8
    // function that returns an array of two elements: the current state and a function to update it
    let [sizes, setSizes] = React.useState(window.Inventory.allSizes);
    let [color, setColor] = React.useState("red");

    return (
      // Can't use class but className
      <div className="customizer">
        <div className="product-image">
          <ProductImage color={color} />
        </div>

        <div className="selectors">
          <SizeSelector size={size} sizes={sizes} />
        </div>

      </div>
    );
  }


  // ReactDOM.render takes two arguments: element to be rendered and where the element should go
  ReactDOM.render(<ProductCustomizer />, document.getElementById('react-root'));
})();
